### ISSUE TITLE
Use XDG Base Directory Specification for configuration and any other file

### ISSUE THREAD

**Issue by 0x00cl** [hackerfactor/SEAL-C#3]
Although its common for programs to add _dot files_ to $HOME such as configurations or directories which contains configuration files, It usually clutters the $HOME directory and makes finding and backing up configuration files, and other important files harder as they could be anywhere in your $HOME.

[XDG Base Directory Specification (BDS)](https://specifications.freedesktop.org/basedir-spec/latest/) provides variables that allows the user to configure or defaults to keep $HOME from getting cluttered and and organize files used by programs.

[Arch Linux wiki provides a simpler description of the variables](https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories).

I noticed that the default location for the configuration file is `$HOME/.seal.cfg`. Instead it should use `$XDG_CONFIG_HOME` which if not set, should default to `$HOME/.config`

PD. The arch wiki also provides a list of software that supports XDG BDS in case you need examples.

**Comment by hackerfactor** [comment]
How about $XDG_CONFIG_HOME

But if that doesn't exist, then check if $HOME/.config/ exists as a directory.  If it exists, then use $HOME/.config/SEAL/config

If $HOME/.config does not exist, then use $HOME/.seal.cfg

I don't like the long list of conditional locations, but I also understand your desire to not clutter $HOME.

Does this solve the problem for you? If so, I can code it up in an hour.

**Comment by 0x00cl** [comment]
It doesn't need to be a _long_ list of conditionals, from what I saw in other projects such as [binwalk](https://github.com/ReFirmLabs/binwalk/commit/2051757#diff-178583784ab6d8149c923796c21d69c92ae6a0ca3c1c60acb0209bceac41719fR110), [aplvl](https://github.com/naihe2010/apvlv/commit/ed0e0112b05b0cafa13ca4e215ee559c82194caf#diff-7b9337fcff3141736997afd31f7a2764b3538153922282c8407af5f43d543cabR83) and [htop](https://github.com/hishamhm/htop/commit/93233a6#diff-1d86c20bae532e692419397a32f62b190559e28b489638363639df82c0931adfR220) they check if $XDG_CONFIG_HOME is set. If its not then it simply uses `$HOME/.config/` (From my understanding if $HOME/.config doesn't exist it should create it automatically, to avoid having to also check whether .config exists)

But yes, supporting $XDG_CONFIG_HOME as the default location does solve the problem.

**Comment by hackerfactor** [comment]
Thank you.

I've made the change in https://github.com/hackerfactor/SEAL-C/commit/e3fac7c26818bb23a76b0dee78e015b495952706
